// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/filesync.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ChunkNumber   int32                  `protobuf:"varint,3,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	IsLast        bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_protos_filesync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_protos_filesync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_protos_filesync_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *FileChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type FolderChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foldername    string                 `protobuf:"bytes,1,opt,name=foldername,proto3" json:"foldername,omitempty"`
	FileChunk     *FileChunk             `protobuf:"bytes,2,opt,name=file_chunk,json=fileChunk,proto3" json:"file_chunk,omitempty"`
	SenderIp      string                 `protobuf:"bytes,3,opt,name=sender_ip,json=senderIp,proto3" json:"sender_ip,omitempty"` // <-- new field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderChunk) Reset() {
	*x = FolderChunk{}
	mi := &file_protos_filesync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderChunk) ProtoMessage() {}

func (x *FolderChunk) ProtoReflect() protoreflect.Message {
	mi := &file_protos_filesync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderChunk.ProtoReflect.Descriptor instead.
func (*FolderChunk) Descriptor() ([]byte, []int) {
	return file_protos_filesync_proto_rawDescGZIP(), []int{1}
}

func (x *FolderChunk) GetFoldername() string {
	if x != nil {
		return x.Foldername
	}
	return ""
}

func (x *FolderChunk) GetFileChunk() *FileChunk {
	if x != nil {
		return x.FileChunk
	}
	return nil
}

func (x *FolderChunk) GetSenderIp() string {
	if x != nil {
		return x.SenderIp
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_protos_filesync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_protos_filesync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_protos_filesync_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	RequesterName string                 `protobuf:"bytes,2,opt,name=requester_name,json=requesterName,proto3" json:"requester_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	mi := &file_protos_filesync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_filesync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_protos_filesync_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *ConnectionRequest) GetRequesterName() string {
	if x != nil {
		return x.RequesterName
	}
	return ""
}

type ConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionResponse) Reset() {
	*x = ConnectionResponse{}
	mi := &file_protos_filesync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResponse) ProtoMessage() {}

func (x *ConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_filesync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResponse.ProtoReflect.Descriptor instead.
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return file_protos_filesync_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=filePath,proto3" json:"filePath,omitempty"`
	IP            string                 `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_protos_filesync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_filesync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_protos_filesync_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UpdateRequest) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *UpdateRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_protos_filesync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_filesync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_protos_filesync_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FileUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUpdate) Reset() {
	*x = FileUpdate{}
	mi := &file_protos_filesync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUpdate) ProtoMessage() {}

func (x *FileUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_protos_filesync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUpdate.ProtoReflect.Descriptor instead.
func (*FileUpdate) Descriptor() ([]byte, []int) {
	return file_protos_filesync_proto_rawDescGZIP(), []int{7}
}

func (x *FileUpdate) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileUpdate) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protos_filesync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_filesync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_filesync_proto_rawDescGZIP(), []int{8}
}

var File_protos_filesync_proto protoreflect.FileDescriptor

const file_protos_filesync_proto_rawDesc = "" +
	"\n" +
	"\x15protos/filesync.proto\x12\n" +
	"filesyncpb\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\tFileChunk\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fchunk_number\x18\x03 \x01(\x05R\vchunkNumber\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\"\x80\x01\n" +
	"\vFolderChunk\x12\x1e\n" +
	"\n" +
	"foldername\x18\x01 \x01(\tR\n" +
	"foldername\x124\n" +
	"\n" +
	"file_chunk\x18\x02 \x01(\v2\x15.filesyncpb.FileChunkR\tfileChunk\x12\x1b\n" +
	"\tsender_ip\x18\x03 \x01(\tR\bsenderIp\";\n" +
	"\x03Ack\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x11ConnectionRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12%\n" +
	"\x0erequester_name\x18\x02 \x01(\tR\rrequesterName\"J\n" +
	"\x12ConnectionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"u\n" +
	"\rUpdateRequest\x12\x1a\n" +
	"\bfilePath\x18\x01 \x01(\tR\bfilePath\x12\x0e\n" +
	"\x02IP\x18\x02 \x01(\tR\x02IP\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"F\n" +
	"\x0eUpdateResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"v\n" +
	"\n" +
	"FileUpdate\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilePath\x18\x02 \x01(\tR\bfilePath\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\a\n" +
	"\x05Empty2\x98\x03\n" +
	"\x0fFileSyncService\x122\n" +
	"\bSendFile\x12\x15.filesyncpb.FileChunk\x1a\x0f.filesyncpb.Ack\x129\n" +
	"\vReceiveFile\x12\x11.filesyncpb.Empty\x1a\x15.filesyncpb.FileChunk0\x01\x12R\n" +
	"\x11RequestConnection\x12\x1d.filesyncpb.ConnectionRequest\x1a\x1e.filesyncpb.ConnectionResponse\x12;\n" +
	"\rReceiveFolder\x12\x17.filesyncpb.FolderChunk\x1a\x0f.filesyncpb.Ack(\x01\x12F\n" +
	"\rRequestUpdate\x12\x19.filesyncpb.UpdateRequest\x1a\x1a.filesyncpb.UpdateResponse\x12=\n" +
	"\x12ReceiveUpdatedFile\x12\x16.filesyncpb.FileUpdate\x1a\x0f.filesyncpb.AckB\x13Z\x11synthesize/protosb\x06proto3"

var (
	file_protos_filesync_proto_rawDescOnce sync.Once
	file_protos_filesync_proto_rawDescData []byte
)

func file_protos_filesync_proto_rawDescGZIP() []byte {
	file_protos_filesync_proto_rawDescOnce.Do(func() {
		file_protos_filesync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_filesync_proto_rawDesc), len(file_protos_filesync_proto_rawDesc)))
	})
	return file_protos_filesync_proto_rawDescData
}

var file_protos_filesync_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_filesync_proto_goTypes = []any{
	(*FileChunk)(nil),             // 0: filesyncpb.FileChunk
	(*FolderChunk)(nil),           // 1: filesyncpb.FolderChunk
	(*Ack)(nil),                   // 2: filesyncpb.Ack
	(*ConnectionRequest)(nil),     // 3: filesyncpb.ConnectionRequest
	(*ConnectionResponse)(nil),    // 4: filesyncpb.ConnectionResponse
	(*UpdateRequest)(nil),         // 5: filesyncpb.UpdateRequest
	(*UpdateResponse)(nil),        // 6: filesyncpb.UpdateResponse
	(*FileUpdate)(nil),            // 7: filesyncpb.FileUpdate
	(*Empty)(nil),                 // 8: filesyncpb.Empty
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_protos_filesync_proto_depIdxs = []int32{
	0, // 0: filesyncpb.FolderChunk.file_chunk:type_name -> filesyncpb.FileChunk
	9, // 1: filesyncpb.UpdateRequest.timestamp:type_name -> google.protobuf.Timestamp
	9, // 2: filesyncpb.FileUpdate.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: filesyncpb.FileSyncService.SendFile:input_type -> filesyncpb.FileChunk
	8, // 4: filesyncpb.FileSyncService.ReceiveFile:input_type -> filesyncpb.Empty
	3, // 5: filesyncpb.FileSyncService.RequestConnection:input_type -> filesyncpb.ConnectionRequest
	1, // 6: filesyncpb.FileSyncService.ReceiveFolder:input_type -> filesyncpb.FolderChunk
	5, // 7: filesyncpb.FileSyncService.RequestUpdate:input_type -> filesyncpb.UpdateRequest
	7, // 8: filesyncpb.FileSyncService.ReceiveUpdatedFile:input_type -> filesyncpb.FileUpdate
	2, // 9: filesyncpb.FileSyncService.SendFile:output_type -> filesyncpb.Ack
	0, // 10: filesyncpb.FileSyncService.ReceiveFile:output_type -> filesyncpb.FileChunk
	4, // 11: filesyncpb.FileSyncService.RequestConnection:output_type -> filesyncpb.ConnectionResponse
	2, // 12: filesyncpb.FileSyncService.ReceiveFolder:output_type -> filesyncpb.Ack
	6, // 13: filesyncpb.FileSyncService.RequestUpdate:output_type -> filesyncpb.UpdateResponse
	2, // 14: filesyncpb.FileSyncService.ReceiveUpdatedFile:output_type -> filesyncpb.Ack
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_filesync_proto_init() }
func file_protos_filesync_proto_init() {
	if File_protos_filesync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_filesync_proto_rawDesc), len(file_protos_filesync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_filesync_proto_goTypes,
		DependencyIndexes: file_protos_filesync_proto_depIdxs,
		MessageInfos:      file_protos_filesync_proto_msgTypes,
	}.Build()
	File_protos_filesync_proto = out.File
	file_protos_filesync_proto_goTypes = nil
	file_protos_filesync_proto_depIdxs = nil
}
